### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by 3kh0** [EmulatorOS/EmulatorOS.github.io#20]
Hello there!

I have looked through your GitHub repo and I found some things that I believe were taken from my site. I ask that you take them down to respect my work and what I do.
If the original one was blocked then you can contact me and I can give you more links. If you have any questions please feel free to reach out to me!

Thanks!
Echo

**Comment by Burst-lucky077** [comment]
wow just saw this am not apart of this repo but what are the games

**Comment by 3kh0** [comment]
This repo takes the background, and the games. Plus the view counter is stolen from ubg100, this repo is just made by skids, unstar

**Comment by EmulatorOS** [comment]
what are the games?, I remember I took some games but neither you or me own the games. Ill take down the games that you ask me to.

**Comment by 3kh0** [comment]
tunnel rush, there is no game, getaway shootout, George and the printer, game inside a game, cell machine, backrooms, sort the court and 2048

**Comment by EmulatorOS** [comment]
The only ones I remember taking is back rooms, there is no game, and cell machine the rest are games that we both have.

**Comment by 3kh0** [comment]
Ok, just please remove them, thanks!

**Comment by EmulatorOS** [comment]
Ok, Ill take the games down and I asked if I could use the view counter. Sorry for the inconvenience
