### ISSUE TITLE
How to Deploy

### ISSUE THREAD

**Issue by TheR0b0tMan** [EmulatorOS/EmulatorOS.github.io#40]
How do you deploy using GitHub pages?

**Comment by EmulatorOS** [comment]
fork this repository and name it TheR0b0tMan.github.io for your case then follow this [tutorial](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site) and do the same thing for all the repositories [here](https://github.com/EmulatorOS/EmulatorOS.github.io#emulatorosgithubio)
