### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by attaeht** [EmulatorOS/EmulatorOS.github.io#8]
hey emulator os, im currently developing my own proxy website which you can download (so it cant get blocked) and i want to learn how to set up my own ultraviolet proxy. if you can help (i may pay depending on how much you help) please contact attaeht@gmail.com

**Comment by EmulatorOS** [comment]
I can help, check ur gmail

**Comment by attaeht** [comment]
> I can help, check ur gmail

please reply on gmail

**Comment by attaeht** [comment]
Please reply on gmail.
